# Mod Properties
mod.minecraft_version=1.21.11
# Comma separated list of target versions
mod.publishing_target_minecraft_versions=1.21.11

# Dependencies
deps.fabric_loader=[NOT_FABRIC]
deps.fabric_api=[NOT_FABRIC]
deps.fabric_kotlin=[NOT_FABRIC]

deps.neoforge=21.11.26-beta
deps.forge_kotlin=6.0.0
