package de.clickism.clicksigns.sign;

/**
 * Sign type enum
 */
public enum SignType {
    /**
     * Tiled signs are generated by using a single texture,
     * divided into 3x3 tiles, and can be generated for arbitrary sizes.
     */
    TILED,
    /**
     * Custom signs are generated by using a single texture and have a predefined size.
     */
    CUSTOM,
}
